version: "3.9"

services:
  flask_movies_app:
    container_name: flask_movies_app
    image: sql_test_flask:v1.0.0
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres_db:5432/postgres
    depends_on:
      - postgres_db
  postgres_db:
    container_name: postgres_db
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}